### ISSUE TITLE
How to use it for links coming after ajax?

### ISSUE THREAD

**Issue by anupalusoft** [maxailloud/confirm-bootstrap#12]
I am having delete links in table. Table get refresh and link as well thus the `$('.delete').confirModal()` wont fire. 

What is way to handle it after ajax instead of re-initializing? 
Can i modify it to use with:
`$(document).on( "click", '.delete',function(e) `

**Comment by maxailloud** [comment]
Yes your solution could be working I think, using the `confirmAutoOpen` option that will auto open the confirm modal when clicking element.

SOmething like that:

```js
$(document).on( "click", '.delete',function(event) {
    event.preventDefault();
    $(event.target).confirmModal({confirmAutoOpen: true});
});
```

It will automatically fire up the confirm modal, and allow you to use it with newly created element.
