### ISSUE TITLE
Multiple confirm if same link clicked

### ISSUE THREAD

**Issue by anupalusoft** [maxailloud/confirm-bootstrap#13]
When we click the link it shows confirm modal but after closing it if we again open click the link it will show modals. If we again click that same link then it will show confirm modal 3 times. 

Have anyone find this issue?

**Comment by maxailloud** [comment]
Can you add a plunker that reproduce the issue?

**Comment by maxailloud** [comment]
Do you use it like I said on #12 using this code:

```js
$(document).on( "click", '.delete',function(event) {
    event.preventDefault();
    $(event.target).confirmModal({confirmAutoOpen: true});
});
```

Because like this I think it's normal.

I think removing event on element will be nice before adding it, just in case.

**Comment by anupalusoft** [comment]
Yes the same way i did and event is also prevented. But still issue is same. It opening multiple confirm.
I tried to add in jsfiddle but not working through there. Can you please work on it to run atleast. 
https://jsfiddle.net/rqnstce9/9/

**Comment by maxailloud** [comment]
Here a working plunker:
http://plnkr.co/edit/PQqAoCUPM8PHVrglVvpM?p=preview

And actually several modal opened if we click several time on links.
I find a way to solve this issue but I'm not sure about it, test it in the plunker. I'll need to investigate more before pushing something.

**Comment by anupalusoft** [comment]
Plunk is not working.

**Comment by maxailloud** [comment]
It's working for me, maybe try the [embedded view](http://embed.plnkr.co/PQqAoCUPM8PHVrglVvpM/).

**Comment by anupalusoft** [comment]
Yes its working fine in Plunk. I am using bootstrap extended modals and modal manager in my project. Is anyone of this creating issue ? Am doing the same way you told but no Go! 
![image](https://cloud.githubusercontent.com/assets/7344503/8348741/26b39618-1b34-11e5-9a26-4743841e9535.png)

These above queries am using. Maybe it could help us to find this bug.

**Comment by maxailloud** [comment]
So the interaction with other libraries could create conflict.
But as I don't know this libraries I cannot say.

Event with my modification it doesn't solve your issue? The confirm bootstrap file in the plunker is updated.

**Comment by anupalusoft** [comment]
Plunker is working fine. Please tell what change done in confirm bootstrap file so i can paste it in my project file though i bit modified it.

**Comment by maxailloud** [comment]
Line 106 to 110 replaced by:

```js
var modalEvent = function(modalEvent)
{
    modalEvent.preventDefault();
    confirmModal.modal('show');
};
            
            
if (!options.confirmAutoOpen) {
    confirmLink.on('click', modalEvent);
}
```

**Comment by anupalusoft** [comment]
:) You did it. I just replaced with above and now it working perfect. Job done!

**Comment by maxailloud** [comment]
You're welcome.
Just don't forget that for now this modification is not in the repository, a better solution could be great and I don't have time for now.
