### ISSUE TITLE
Broken Demo 

### ISSUE THREAD

**Issue by vpArth** [maxailloud/confirm-bootstrap#18]
[This script](https://github.com/maxailloud/confirm-bootstrap/blob/gh-pages/index.html#L194) should be loaded as `https` or `//`.  
Other case `jQuery` cannot be loaded into [https demo page](https://maxailloud.github.io/confirm-bootstrap/) because mixed content browser violation.

`[gh-pages]`

**Comment by maxailloud** [comment]
Thank you for the heads up.

Https mode in gh-pages is really new, will think about it now.

**Comment by jotaroita** [comment]
documentation error in home page. miss a comma, the code is broken at line:

` confirmStyle     : 'primary'`

**Comment by maxailloud** [comment]
Thank you @jotaroita, fix now.
