### ISSUE TITLE
Not unique modalId in some cases.

### ISSUE THREAD

**Issue by pyotruk** [maxailloud/confirm-bootstrap#8]
Line 63:             var modalId = "confirmModal" + parseInt(time + index);
1. I have few different modals on the page with different launching elements
2. index equals 0 everytime
3. time is Int and index is Int
4. time is number of milliseconds

I fixed it like this:
var modalId = "confirmModal" + Math.floor(Math.random()*(1e+9));

Hope it is useful for you.
Thank you for your great plugin!

**Comment by maxailloud** [comment]
If you make a Pull Request I'll gladly merge it.
